Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> def sawatdee() :
	print('สวัสดีจ้าาาา')

	
>>> sawatdee()
สวัสดีจ้าาาา
>>> sawatdee()
สวัสดีจ้าาาา
>>> def hello(name):
	print('สวัสดีคุณ' + name)

	
>>> def hello(name):
	print('สวัสดีคุณ' + name)

	
>>> hello('mint')
สวัสดีคุณmint
>>> 
>>> def kaomankai(menu='ข้าวมันไก่'):
	print('ซื้อ'+menu)
	print('1 จาน')

	
>>> kaomankai()
ซื้อข้าวมันไก่
1 จาน
>>> kaomankai('ข้าวมันไก่ไม่หนัง')
ซื้อข้าวมันไก่ไม่หนัง
1 จาน
>>> 
= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
cat:แมว

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
cat:แมว
cat:แมว

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
Dog:แมว

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py", line 32, in Translate
    meaning = Translate(vocab,dest = 'th')
TypeError: Translate() got an unexpected keyword argument 'dest'

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py", line 32, in Translate
    meaning = Translate(vocab,dest = 'th')
TypeError: Translate() got an unexpected keyword argument 'dest'

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py", line 32, in Translate
    meaning = translator.translate(vocab,dest = 'th')
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py", line 32, in Translate
    meaning = translator.translate(vocab,dest = 'th')
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

= RESTART: D:/วิศวะ สอนคำนวน/python bootcame 2021 _basic EP1/GUI_TRAN.py
